name: flowdas
channels:
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - annotated-types==0.7.0
    - asttokens==3.0.0
    - bokeh==3.6.2
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - click==8.1.8
    - comm==0.2.2
    - contourpy==1.3.1
    - cycler==0.12.1
    - debugpy==1.8.12
    - decorator==5.1.1
    - docker-pycreds==0.4.0
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fonttools==4.55.6
    - gitdb==4.0.12
    - gitpython==3.1.44
    - h5py==3.12.1
    - idna==3.10
    - ipykernel==6.29.5
    - ipython==8.31.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.8
    - livelossplot==0.5.6
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.7
    - nest-asyncio==1.6.0
    - numpy==1.26.4
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.1.0
    - pip==24.2
    - platformdirs==4.3.6
    - pot==0.9.5
    - prompt-toolkit==3.0.50
    - protobuf==5.29.3
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygments==2.19.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzmq==26.2.1
    - requests==2.32.3
    - scipy==1.15.1
    - seaborn==0.13.2
    - sentry-sdk==2.22.0
    - setproctitle==1.3.4
    - setuptools==72.1.0
    - six==1.17.0
    - smmap==5.0.2
    - stack-data==0.6.3
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - urllib3==2.3.0
    - wandb==0.19.6
    - wcwidth==0.2.13
    - wheel==0.43.0
    - xyzservices==2025.1.0
    - zuko==1.3.1
